"""RQ3 reuses the TPCH RQ1 query definitions and selectivity bands."""

from workload_spec.generate_tpch_rq1_specs import (  # re-export for parsers/consumers
    COLUMN_CONFIGS,
    QUERY_DEFS,
    SELECTIVITY_BANDS,
)

# Notes:
# - RQ3 specs were generated by copying/renaming a subset of RQ1 specs.
# - Keep these exports in sync with generate_tpch_rq1_specs.
